config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  # Defines the root path route ("/")
  # root "articles#index"
  resources :noris do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  root 'noris#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :nori
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :nori
  belongs_to :user
  validates_uniqueness_of :nori_id, scope: :user_id

end

app/models/nori.rb
class Nori < ApplicationRecord
  
     #norisテーブルから中間テーブルに対する関連付け
  has_many :nori_tag_relations, dependent: :destroy
  #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :nori_tag_relations, dependent: :destroy
  belongs_to :user
  # 追記箇所
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy

    mount_uploader :image, ImageUploader
end

app/models/nori_tag_relation.rb
class NoriTagRelation < ApplicationRecord
  belongs_to :nori
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :nori_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :noris, through: :nori_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :noris, dependent: :destroy
         has_many :likes, dependent: :destroy
  has_many :liked_noris, through: :likes, source: :nori
  has_many :comments, dependent: :destroy
  has_many :tweets, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記

  def already_liked?(nori)
    self.likes.exists?(nori_id: nori.id)
  end

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      # deviseコントローラーにストロングパラメータを追加する          
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile,:image])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      nori = Nori.find(params[:nori_id])
      comment = nori.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(nori_id: params[:nori_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(nori_id: params[:nori_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    
end

app/controllers/noris_controller.rb
class NorisController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
    def index
        @noris = Nori.all 
        if params[:search] != nil && params[:search] != ''
          #部分検索かつ複数検索
          search = params[:search]
          @noris = Nori.where("shop_name LIKE ? OR name LIKE ?", "%#{search}%", "%#{search}%")
        else
          @noris = Nori.all
        end
  
  
        if params[:tag_ids]
        @noris = []
        params[:tag_ids].each do |key, value|      
          @noris += Tag.find_by(name: key).noris if value == "1"
        end
        @noris.uniq!
      end
  
    end
    def new
        @nori = Nori.new
      end
    
      def create
        nori = Nori.new(nori_params)
        nori.user_id = current_user.id
      
        if nori.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
      def show
        @nori = Nori.find(params[:id])
        @comments = @nori.comments
        @comment = Comment.new
      end
      def edit
        @nori = Nori.find(params[:id])
      end
      
      def update
        nori = Nori.find(params[:id])
        if nori.update(nori_params)
          redirect_to :action => "show", :id => nori.id
        else
          redirect_to :action => "new"
        end
      end
      def destroy
        nori = Nori.find(params[:id])
        nori.destroy
        redirect_to action: :index
      end
    
    
      private
      def nori_params
          params.require(:nori).permit(:address, :shop_name, :price, :name, :about, :image, :hoshi, :lat, :lng ,tag_ids: [])
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/noris_helper.rb
module NorisHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
      end
     
     
end

app/helpers/ramens_helper.rb
module RamensHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mashimashi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>
 <header>
 <div class="home">
          <%= link_to noris_path do %>
            <%= image_tag 'icon2.jpg', alt: "俺のラーメン", class: "homeicon" %>
          <%end%>
          <h1>俺のラーメン</h1>
  </div>
 
  <div class="header-list">
   <ul>

    <div class="roguout">
      <% if user_signed_in? %>
      <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "新規登録", new_user_registration_path %></li>
      <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>

  <footer>
    <p>Copyright © 俺のラーメン All Rights Reserved.</p>
  </footer>

</body>

 
</html>

app/views/noris/edit.html.erb
<h1>ラーメンサイト</h1>
<h3>新規投稿ページ</h3>
<%= form_for @nori do |f| %>

    <div class="field">
     <%= f.label :address %>
     <%= f.text_field :address, :size => 30 %>
    </div>

  <div class="field">
    <%= f.label :shop_name %>
    <%= f.text_field :shop_name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :price  %>
    <%= f.number_field :price, :size => 10 %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :about  %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

  <div class='form-group'>
   <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class='form-check'>
          <%= tag.label class: 'form-check-label' do %>
              <%= tag.check_box class: 'form-check-input' %>
              <%= tag.text %>
          <% end %>
      </div>
   <% end %>
  </div>

  <div class="field">
     <%= f.label :image %>
     <%= f.file_field :image %>
  </div>


  <%= f.submit "投稿する" %>
  
 <% end %>
  
  <%= link_to "トップページに戻る", noris_path %>

app/views/noris/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<div class="img-frame">
 <div class="img-01"></div>
 <div class="img-02"></div>
 <div class="img-03"></div>
 </div>



<div class="kensaku-container">
<h1>投稿を検索</h1>
<br>
<div class="search_box">
 <%= form_tag({controller:"noris",action:"index"}, method: :get) do %>
   <input type="text" placeholder="ここにキーワード">
   <%= submit_tag 'キーワードで検索'  %>
<% end %>
</div>

<div class="kensaku">
<br>
<%= form_tag({controller:"noris",action:"index"}, method: :get) do %>
  <% Tag.all.each do |t| %>
      <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
  <% end %>
  <%= submit_tag '条件で検索' %>
<% end %>
</div>
<div class="link">
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

<% if user_signed_in? %>
<%= link_to "新規投稿", new_nori_path %>
<% end %>
</div>
</div>


<div class="noris-container">
</div>
<h1>投稿一覧</h1>
  <% @noris.each do |t| %>
    <div class="nori">
      <div class="main-box">
        <div class="left-container">
        <%= image_tag t.image_url, size: "350x300" if t.image? %>
      </div>
      <div class="right-container">
      <ul>
      <div>
      <li><h2>総合評価：
      <span class="star-rating">
        <span class="star-rating-front" style="width: <%= getPercent(t.hoshi) %>%;">★★★★★</span>
        <span class="star-rating-back">★★★★★</span>
      </span> 
      </h2></li>
      </div>
         <li>住所：<%= t.address %></li>
         <li>店名：<%= t.shop_name %></li>
         <li>価格：<%= t.price %></li>
         <li>商品名：<%= t.name %></li>
         <li>詳細：<%= t.about %></li>
         <li>投稿者：<%= t.user.name %></li>
        </ul>
      
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
              <%= button_to nori_like_path(id: t.id, nori_id: t.id), method: :delete do %>
                  <p>いいねを取り消す</p><%= t.likes.count %>
              <% end %>
          <% else %>
              <%= button_to nori_likes_path(id: t.id, nori_id: t.id), method: :post do %>
                <p>いいね</p><%= t.likes.count %>
              <% end %>
          <% end %>
        <% else %>
        <p>いいねの数 = </p><%= t.likes.count %>
        <% end %>
      <%= t.created_at %>
      <%= link_to "詳細ページへ", nori_path(t.id),data: { turbo: false } %>
      <% if user_signed_in? && current_user.id == t.user_id %>
         <%= link_to "編集する", edit_nori_path(t.id) %>
         <%= button_to "削除する", nori_path(t.id), method: :delete %>
      <% end %> 
        </div>
      </div>
      <p class="time"><%= t.created_at %></p>
    </div>
  <% end %>
</div>

app/views/noris/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>
<div class="toukou">
<h1>新規投稿ページ</h1>
<%= form_for @nori do |f| %>

  <h5>総合評価</h5>
  <div class="post_form">
   <%= f.radio_button :hoshi, 5 ,id: 'star1'%>
   <label for="star1"><span class="text">最高</span>★</label>

   <%= f.radio_button :hoshi, 4 ,id: 'star2'%>
   <label for="star2"><span class="text">良い</span>★</label>

   <%= f.radio_button :hoshi, 3 ,id: 'star3'%>
   <label for="star3"><span class="text">普通</span>★</label>

   <%= f.radio_button :hoshi, 2 ,id: 'star4'%>
   <label for="star4"><span class="text">悪い</span>★</label>

   <%= f.radio_button :hoshi, 1 ,id: 'star5'%>
   <label for="star5"><span class="text">最悪</span>★</label>
</div>

    <div class="field">
     <%= f.label :address %>
     <%= f.text_field :address, :size => 30 %>
    </div>

  <div class="field">
    <%= f.label :shop_name %>
    <%= f.text_field :shop_name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :price  %>
    <%= f.number_field :price, :size => 10 %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :about  %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

  <div class="field">
     <%= f.label :image %>
     <%= f.file_field :image %>
  </div>

  <div class='form-group'>
   <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class='form-check'>
          <%= tag.label class: 'form-check-label' do %>
              <%= tag.check_box class: 'form-check-input' %>
              <%= tag.text %>
          <% end %>
      </div>
   <% end %>
  </div>

 
    <div class="actions">
   
      <%= f.label :lat,"緯度" %>
      <%= f.text_field :lat,:value =>"緯度", id: :lat %>
      <%= f.label :lng,"経度" %>
      <%= f.text_field :lng,:value =>"経度", id: :lng %>
    </div>
  
  <h2>Map</h2>
  
  <input id="address" type="textbox" value="GeekSalon">
  <input type="button" value="検索" onclick="codeAddress()">
  <p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
  <div id='map'></div>
  
  <style>
  #map {
    height: 600px;
    width: 600px;
  }
  </style>
  
  <script>
  //初期マップの設定
  let map
  let marker
  function initMap(){
    geocoder = new google.maps.Geocoder()
  
    map = new google.maps.Map(document.getElementById('map'), {
      center:  {lat: 35.6803997, lng:139.7690174},  //東京
      zoom: 15,
      
    });
  }
  
  //検索後のマップ作成
  let geocoder
  let aft
  function codeAddress(){
    let inputAddress = document.getElementById('address').value;
    geocoder.geocode( { 'address': inputAddress}, function(results, status) {
      if (status == 'OK') {
          //マーカーが複数できないようにする
          if (aft == true){
              marker.setMap(null);
          }
  
          //新しくマーカーを作成する
          map.setCenter(results[0].geometry.location);
              marker = new google.maps.Marker({
              map: map,
              position: results[0].geometry.location,
              draggable: true	// ドラッグ可能にする
          });
  
          //二度目以降か判断
          aft = true
  
          //検索した時に緯度経度を入力する
          document.getElementById('lat').value = results[0].geometry.location.lat();
          document.getElementById('lng').value = results[0].geometry.location.lng();
  
          // マーカーのドロップ（ドラッグ終了）時のイベント
          google.maps.event.addListener( marker, 'dragend', function(ev){
              // イベントの引数evの、プロパティ.latLngが緯度経度
              document.getElementById('lat').value = ev.latLng.lat();
              document.getElementById('lng').value = ev.latLng.lng();
          });
      } else {
        alert('該当する結果がありませんでした：' + status);
      }
    });   
  }
  
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBimL6F9mKgTt69QddU3Hu6WdzQKsVhYkc&callback=initMap" async defer></script>
  

  <%= f.submit "投稿する" %>
  
 <% end %>
 </div>
  

app/views/noris/show.html.erb
<div class="show-container">
<h1>投稿の詳細</h1>
<br>
  投稿者：<%= @nori.user.name %>
  住所：<%= @nori.address %> 
  店名：<%= @nori.shop_name %>
  価格：<%= @nori.price %>
  商品名：<%= @nori.name %>
  詳細：<%= @nori.about %>
  タグ：<% @nori.tags.each do |tag| %>
    <span><%= tag.name %></span>
  <% end %>

  <p><%= @nori.created_at %></p>

  <% if user_signed_in? %>
      <% if current_user.already_liked?(@nori) %>
        <%= button_to nori_like_path(@nori), method: :delete do %>
          <p>いいねを取り消す</p><%= @nori.likes.count %>
        <% end %>
      <% else %>
        <%= button_to nori_likes_path(@nori), method: :post do %>
          <p>いいね</p><%= @nori.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <p>いいねの数 = </p><%= @nori.likes.count %>
    <% end %>
  <% if user_signed_in? %>
    <%= link_to "編集する", edit_nori_path(@nori.id) %>
  <% end %>
</div>
<div class="googlemap">
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<!-- js部分 -->
<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: <%= @nori.lat %>, lng: <%= @nori.lng %>},
    zoom: 15,
  });

   marker = new google.maps.Marker({
    position:  {lat: <%= @nori.lat %>, lng: <%= @nori.lng %>},
    map: map
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBimL6F9mKgTt69QddU3Hu6WdzQKsVhYkc&callback=initMap" async defer></script>
</div>

<div class="iine">
<h2>いいねしたユーザー</h2>
<% @nori.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
</div>

<div class="comment-wrapper">
  <h2>コメント一覧</h2>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@nori, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログインはこちら", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録はこちら", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れた方はこちら", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="profile_box">
  <div class="box-title">MYプロフィール</div>
  <div class="profile_center">
<%= image_tag @user.image_url, size: "250x200" if @user.image? %> 
  </div>
  <ul>
    <li>名前 : <%= @user.name %></li>
    <li>メールアドレス：<%= @user.email %></li>
    <li>プロフィール： <%= @user.profile %></li>
  </ul>
  <div class="hensyuu">
   <% if current_user.id == @user.id %>
   <%= link_to "編集する", edit_user_registration_path %>
  </div>
<% end %>
</div>
<div class="zentai">
<div class="toukou">
<h2>ユーザーの投稿一覧</h2>
<br>
<br>
<br>
  <% @user.noris.each do |t| %>
      <div class="last">
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
          <div>名前：<%= t.user.name %></div>
          <div>メールアドレス：<%= t.user.email %></div>
          <div>住所：<%= t.address %></div>
          <div>ショップ名：<%= t.shop_name %></div>
          <div>価格：<%= t.price %></div>
          <div>商品名：<%= t.name %></div>
          <div>投稿者コメント：<%= t.about %></div>
          
      <% end %>
      </div>
</div>

<div class="iine">
  <h2>ユーザーがいいねした投稿一覧</h2>
  <br>
  <br>
  <br>
  <% @user.liked_noris.each do |t| %>
    <div class="like">
        <%= image_tag t.image_url, size: "250x200" if t.image? %>
    </div>
    <div class="last2">
      <div>名前：<%= t.user.name %></div>
      <div>メールアドレス：<%= t.user.email %></div>
      <div>住所：<%= t.address %></div>
      <div>ショップ名：<%= t.shop_name %></div>
      <div>価格：<%= t.price %></div>
      <div>商品名：<%= t.name %></div>
      <div>投稿者コメント：<%= t.about %></div>
    </div>
  <% end %>
</div>
</div>
<!-- ここまで-->
<br>
<%= link_to "トップページに戻る", noris_path %>